
API_SERVER = 'http://127.0.0.1/api/v1'
API_SERVER_LOGIN=API_SERVER+"/auth/login"

LOGIN_MENU_DESCRIPTION = 'DOGHOUSE Login'
LOGIN_ENTRY = 'login'
CONTINUE_WITHOUT_LOGIN_ENTRY = 'continue without login'
REGISTER_ENTRY = 'register'
EXIT_ENTRY = 'exit'

USER_MENU_DESCRIPTION = 'DOGHOUSE '
SHOW_DOGS_ENTRY = 'show dogs'
SHOW_PREFERENCES_ENTRY = 'show preferences'
ADD_PREFERENCE_ENTRY = 'add preference'
REMOVE_PREFERENCE_ENTRY = 'remove preference'
LOGOUT_ENTRY = 'logout'

NOT_LOGGED_MENU_DESCRIPTION = 'DOGHOUSE'

ADMIN_MENU_DESCRIPTION='DOGHOUSE'
ADD_DOG_ENTRY='add dog'
REMOVE_DOG_ENTRY='remove dog'

EXIT_MESSAGE = 'Bye!'
LOGOUT_MESSAGE = 'Logged out'


DEFAULT_TOKEN_VALUE='notloggedtoken00000000000000000000000000'


